POST http://localhost:3000/api/blogs
content-type: application/json
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlc3RhYWphIiwiaWQiOiI1YzY2ZTNhMjNhZGY3YjIzMGZmNzMwMTgiLCJpYXQiOjE1NTAyNDg1ODl9.tve_1tz5oe0kDLB1bZuFpXDHdaE7oFfnAL3BdAyAtzA

{
    "title": "asd",
    "author": "asd",
    "url": "asd",
    "likes": 15,
    "userId": "5c66c0efeb3b1e14aef5fe8d"
}
